name = "placement-cms"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "placement-cms-prod"

[env.staging]
name = "placement-cms-staging"

[[d1_databases]]
binding = "DB"
database_name = "placement-cms-db"
database_id = "your-database-id"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"

[build]
command = "npm run build"

[site]
bucket = "./dist"
