name = "placement-cms-v2"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"
APP_NAME = "Placement CMS"

# Uncomment and configure after creating resources
# [[kv_namespaces]]
# binding = "PLACEMENT_DATA"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# [[d1_databases]]
# binding = "DB"
# database_name = "placement-cms-db"
# database_id = "your-database-id"
